# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    ac_platform.antispam:
        class: CA\BlogBundle\Antispam\CAAntispam

    app.user_voter:
        class:  CA\BlogBundle\Security\UserVoter
        arguments: ['@security.access.decision_manager']
        public: false    
        tags:
            - { name: security.voter }
