user_index:
    path:     /
    defaults: { _controller: "CABlogBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "CABlogBundle:User:show" }
    methods:  GET
    requirements: 
      id: '\d+'

user_show_bis:
    path:     /{username}/show
    defaults: { _controller: "CABlogBundle:User:showByUsername", username: null }
    methods : GET
    
user_new:
    path:     /new
    defaults: { _controller: "CABlogBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "CABlogBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "CABlogBundle:User:delete" }
    methods:  DELETE

user_profile:
    path:     /{id}
    defaults: { _controller: CABlogBundle:User:profile, id: null }
    methods : GET
    requirements: 
      id: '\d+'





